// =============================================================
//  protocol.h — Wire packet definition shared by all firmware.
//  Do NOT edit this file; it must be identical on every board.
// =============================================================
#pragma once

#include <stdint.h>

#ifndef NATIVE_TEST
#  include <esp_idf_version.h>
// Require Arduino-ESP32 core 3.x (IDF 5.x) for esp_now_recv_info_t RSSI API.
static_assert(ESP_IDF_VERSION_MAJOR >= 5,
              "This firmware requires Arduino-ESP32 core 3.x (IDF 5.x or newer).");
#endif

static constexpr uint8_t PKT_MAGIC = 0xA5;
static constexpr uint8_t PKT_VER   = 1;

enum class PktType : uint8_t {
    CHAT         = 0,  // Normal chat message
    SMITH_BEACON = 1,  // Smith proximity beacon (no text needed)
    SMITH_CHAT   = 2,  // Smith impersonation / corruption
};

// Packed to guarantee identical layout on every ESP32 variant.
#pragma pack(push, 1)
struct Pkt {
    uint8_t  magic;       // Always PKT_MAGIC (0xA5)
    uint8_t  ver;         // Protocol version
    uint8_t  type;        // PktType cast to uint8_t
    uint8_t  node_id;     // Sender node ID (1-50; Smith uses 99)
    uint8_t  color_idx;   // Index into palette (node_id % N_COLORS)
    uint16_t seq;         // Per-sender sequence counter (wraps at 65535)
    uint8_t  len;         // Actual text length (0 for beacons)
    char     text[180];   // Message text, null-terminated
};
#pragma pack(pop)

static_assert(sizeof(Pkt) <= 250,
              "Pkt exceeds ESP-NOW max payload of 250 bytes.");
